### ISSUE TITLE
Evaluation Metrics described in the Paper

### ISSUE THREAD

**Issue by prateeky2806** [interpretml/DiCE#170]
Hi, I am working with DICE as a baseline model and I am trying to reach a state where I can replicate results in Figure-1 for any of the datasets in the [paper](https://arxiv.org/pdf/1905.07697.pdf). Can you point me to the part which computes the different proposed metrics (validity, proximity, sparsity and diversity)? 

Thanks,
Prateek

**Comment by amit-sharma** [comment]
@raam93 can you guide @prateeky2806 here on steps to reproduce?

**Comment by amit-sharma** [comment]
@prateeky2806 you can follow this repo to reproduce all the metrics https://github.com/raam93/DiCE_evaluations

One thing to note: this code is only compatible with the first release of DiCE. So you'll need to install this version: https://github.com/interpretml/DiCE/releases/tag/v0.2

**Comment by prateeky2806** [comment]
Thanks @amit-sharma for the help. I can work with this to reproduce the results and go ahead with my work.  

Thanks,
Prateek

**Comment by xueyagaga** [comment]
Dear Author, I would like to ask if there is any mature library or package for %Valid CFs, diversity, proximity, and sparsity evaluation, similar to the sklearn.metrics.
Since I am new to the field of algorithmic recourse, I really don't know how to install the first release of DiCE (v 0.2). So in fact I'm having trouble running this code, and I'm sorry for asking such a slothful question.
Best regards

> @prateeky2806 you can follow this repo to reproduce all the metrics https://github.com/raam93/DiCE_evaluations
> 
> One thing to note: this code is only compatible with the first release of DiCE. So you'll need to install this version: https://github.com/interpretml/DiCE/releases/tag/v0.2
