### ISSUE TITLE
Support for XGBoost   with metadata

### ISSUE THREAD

**Issue by jtonglet** [interpretml/DiCE#200]
Does DiCE allow to work with XGBoost?

I've tried to run it using only  with the metadata properties of the features and got the following error :
![image](https://user-images.githubusercontent.com/49620076/128307015-349c9278-2340-417c-8b54-e90ade382e3a.png)

**Comment by amit-sharma** [comment]
DiCE works with any model that follows sklearn's predict API. 

The error is because you are using the private interface, which is useful only in some privacy scenarios where you do not have access to the train data. Instead, can you try passing in the xgboost_model to the DiCE constructor as in the [getting started example](https://github.com/interpretml/DiCE/blob/master/docs/source/notebooks/DiCE_getting_started.ipynb)?
```
# Using sklearn backend
m = dice_ml.Model(model=xgboost_model, backend="sklearn") # xgboost_model.predict() returns the output
# Using method=random for generating CFs
exp = dice_ml.Dice(d, m, method="random")
```
