### ISSUE TITLE
Auto one-hot encoding?

### ISSUE THREAD

**Issue by cdeterman** [interpretml/DiCE#256]
I have a large training dataset (ie. >1M) that contains only int64 and float64 data types.  However, when I pass the dataframe and a limited list of features I am interested in it errors out due to being unable to allocate over 1TB of memory for a massize 1Mx1M matrix.  Looking at the stack trace that is provided after the error I see numerous points where it is trying to dummy encode features using one-hot encoding.  Given that I have no continuous features, I have no idea why this is the case.  Any insight would be appreciated.  Below is my basic pseudo code

```python
# note this is only of small subset several more within the trained model
vars_for_cfs = ['list', 'of', 'features']
d = dice_d(dataframe=train_df, continuous_features=vars_for_cfs, outcome_name='target')

mdl = load('my/model/path')
m = dice_m(mdl, backend='sklearn')
exp = Dice(d, m)
```

Please let me know what I am overlooking to avoid this unintented overhead.

**Comment by gaugup** [comment]
@cdeterman, could try setting `features_to_vary` while generating counterfactuals instead of setting `continuous_features` in data_d? If all of your features are continuous, then you don't need to set the `continuous_features` parameter. DiCE would treat all of your features as continuous and would not try to auto one-hot encode.

```
# Changing only age and education
e2 = exp.generate_counterfactuals(x_test[0:1],
                                  total_CFs=2,
                                  desired_class="opposite",
                                  **features_to_vary**=["education", "occupation"]
                                  )
e2.visualize_as_dataframe(show_only_changes=True)
```

You can use the notebook https://github.com/interpretml/DiCE/blob/master/docs/source/notebooks/DiCE_getting_started.ipynb as a point of reference.

Let us know if the above idea helps with generation of counterfactuals.

Regards,
Gaurav

**Comment by cdeterman** [comment]
@gaugup thank you, however, if I remove the `continuous_features` argument and try to continue with just the `features_to_vary` I get a `ValueError: continuous_features should be provided`.  Any further thoughts?

**Comment by gaugup** [comment]
@cdeterman, sorry you should specify all the features names in your training data (excluding the target) in the list for continous features. Just that the **features_to_vary** should have the features that you intend to vary for the counterfactuals.

Regards,

**Comment by cdeterman** [comment]
@gaugup thank you, this seems to have resolved the issue.

**Comment by gaugup** [comment]
Great to hear this.

Regards,
