### ISSUE TITLE
Binary classification using Pytorch

### ISSUE THREAD

**Issue by UrjaPawar** [interpretml/DiCE#315]
Hi, 

While generating counterfactuals for a binary PyTorch classifier, I observed that the predict function only returns a single output (list with 1 element), as it is trimmed based on a number of output nodes: 
dice_pytorch.py
![image](https://user-images.githubusercontent.com/16853965/181622318-daf27d96-5c6f-4cae-9c55-86cb3eeb7a10.png)

Now, in explainer_base.py, we again see a check based on output nodes (in my case = 2), and so it throws an out of index error (line highlighted) as it is trying to access index = 1, whereas out model_score list is only having one element trimmed in dice_pytorch.py

![image](https://user-images.githubusercontent.com/16853965/181622537-d4847b9d-f1ac-457d-ade1-ba61129998b5.png)

Any information on this will be appreciated

**Comment by amit-sharma** [comment]
This is fixed in PR #261  and #312. You can try checkout the branch [amshar/support-private-data-for-sklearn-models](https://github.com/interpretml/DiCE/tree/amshar/support-private-data-for-sklearn-models)---that should work for your problem. 
It will be soon pushed for a release.

If it does not work, let me know
