### ISSUE TITLE
Number of Counterfactual Examples

### ISSUE THREAD

**Issue by HengQuan1997** [interpretml/DiCE#37]
Can I generate more than 4 counterfactual explanations with the Dice package?

All Dice examples have exactly 4 counterfactual explanations via the "total_CFs=4" code.

Changing "total_CFs" to different numbers will cause errors as well.

Thanks

**Comment by raam93** [comment]
Can you post the error you are getting? You can generate as many counterfactuals as you want depending on the resources you have. We have tested till100 CFs.

**Comment by HengQuan1997** [comment]
> Can you post the error you are getting? You can generate as many counterfactuals as you want depending on the resources you have. We have tested till100 CFs.
<img width="738" alt="Dice Error" src="https://user-images.githubusercontent.com/68982226/92469622-b2ff7380-f207-11ea-9f8c-c31fa1c66fcb.PNG">

Hi Raam. I got a "IndexError: list index out of range" if I change "total_CFs=4" to "total_CFs=10".

This error came from your US income demo. This is the demon link: https://github.com/interpretml/DiCE/blob/master/docs/source/notebooks/DiCE_with_advanced_options.ipynb

Thanks very much.

**Comment by raam93** [comment]
Hey @HengQuan1997, sorry that was a bug in the previous version of DiCE. Can you please update with the latest version and check again?

**Comment by HengQuan1997** [comment]
> Hey @HengQuan1997, sorry that was a bug in the previous version of DiCE. Can you please update with the latest version and check again?

Hi Raam93. Now, Dice is able to generate 5 counterfactuals for every dataset. However, the index error will still occur if "total_CFs" is more than 5.

Thanks very much.

**Comment by raam93** [comment]
Hey @HengQuan1997, I'm sorry but I think you still are using the old version because the `initialize_CFs()` method in the latest version of dice_tensorflow2.py (https://github.com/interpretml/DiCE/blob/master/dice_ml/explainer_interfaces/dice_tensorflow2.py#L271) is different from what is there in the image you have shared above. If you are using pip, can you re-install once again? we last updated the pip version on 22nd Sept 2020.
