### ISSUE TITLE
One-hot encoding in the Data class is not stateful.

### ISSUE THREAD

**Issue by moyaghini** [interpretml/DiCE#38]
`Data.one_hot_encode_data()` being an alias for `pd.get_dummies(df, columns=categorical_features)` would one-hot-encode every dataframe using the categories present in `df`. This is problematic when you need to one-hot-encode a set of counter-factuals (post-hoc) that do not include all categories of a particular feature.

If pos-hoc pre-processing of data is not intended for the Data class, I suggest prefixing the method with "_", or otherwise include the stateful methods (in this case: a method to use the exact scheme that has been used in encoding the train/test data for arbitrary data).

**Comment by raam93** [comment]
Hey, @moyaghini sorry for the very late response. It's not clear to me when you say the method would one-hot-encode every dataframe? We have drop_first=False in pd.dummies() method so that is the same as one-hot-encoding.

If your question is about constraining the possible values a categorical feature can take, that is still not implemented in DiCE and we are working on that: https://github.com/interpretml/DiCE/issues/28.

**Comment by amit-sharma** [comment]
Closing as the one-hot encoding was updated in v0.5.
