### ISSUE TITLE
Can DiCE support any regression model?

### ISSUE THREAD

**Issue by wangyongjie-ntu** [interpretml/DiCE#40]
Hi, 

Can DiCE support any regression model? E.g., just specifiy the loss function as the MSE loss?

Thanks

**Comment by raam93** [comment]
You can use the `l2_loss' option for `yloss_type' parameter in generate_counterfactuals() method and it will find counterfactuals. However, there will be some inconsistencies with the print summary and some variables of the explanation class because this part of the code was written with classification models in mind. Specifically, the code needs a little tweaking in the areas where `target_cf_class` variable of dice explanation object occurs. I will update them soon but feel free to raise a PR to contribute. Thanks!
