### ISSUE TITLE
'LogisticRegression' object has no attribute backend

### ISSUE THREAD

**Issue by hende8** [interpretml/DiCE#53]
Hey there,
I'm trying to create an exp like this example 
`exp = dice_ml.Dice(data,m)
`
I'm using # XGBClassifier   and # LogisticRegression as prediction model
but all the time I encounter in this error : 
`AttributeError: 'LogisticRegression' object has no attribute 'backend'`
`AttributeError: 'XGBClassifier   ' object has no attribute 'backend'`

Anybody can help me please?I will appreciate a lot! 
Thanks
Hen

**Comment by gaugup** [comment]
Can you share the dice-ml version and a sample notebook?

**Comment by amit-sharma** [comment]
@hende8 you need to create a model object first, before passing it to the `dice_ml.Dice` constructor. I suspect the issue is due to setting `m` as `XGBClassifier` or `LogisticRegression`.  Instead, try this as shown in the [Getting Started](https://github.com/interpretml/DiCE/blob/master/docs/source/notebooks/DiCE_getting_started.ipynb) notebook.

```
lr_clf = LogisticRegression().fit(X, y)
m = dice_ml.Model(model=lr_clf, backend="sklearn")
exp = dice_ml.Dice(data, m)
```

It may also be good to update DiCE to the latest version (0.5), that has better support for sklearn models.
